<a href="https://colab.research.google.com/github/akbarjonovizzatillo36/Reja/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy


In [11]:
del print

In [3]:
import numpy as np

arr = np.array([1, 3, 5, 7])
print('numpy_array:', arr)

numpy_array: [1 3 5 7]


In [13]:
# dtype
a = np.array([1, 2, 3])
print(a.dtype)

int64


In [14]:
# reshape
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)
print("shaped_array:", b)

shaped_array: [[1 2 3]
 [4 5 6]]


In [4]:


# astype()
a = np.array([1, 2, 3])
b = a.astype(float)

print("float:", b)

float: [1. 2. 3.]


In [6]:
# np.zeros(), np.ones() => dummy data

z = np.zeros((2, 3))
o = np.ones((2, 3))

print("zeros:", z)
print("ones:", o)

zeros: [[0. 0. 0.]
 [0. 0. 0.]]
ones: [[1. 1. 1.]
 [1. 1. 1.]]


In [7]:
# ndim
a = np.array([[1, 2], [3, 4]])
print("ndim:", a.ndim)

ndim: 2


In [8]:
# arange()
a = np.arange(1, 7)
print("arange:", a)

arange: [1 2 3 4 5 6]


In [9]:
# sum(), mean(), max(), min()

a = np.array([0, 1, 2, 3, 4])

print("sum:", a.sum())
print("mean:", a.mean())
print("max:", a.max())
print("min:", a.min())

sum: 10
mean: 2.0
max: 4
min: 0


In [10]:
# flatten()

a = np.array([[1, 2], [3, 4]])
print("flatten:", a.flatten())

flatten: [1 2 3 4]


In [11]:
# T (Transpose)

a = np.array([[1, 2], [3, 4]])
print("transpose:", a.T)

transpose: [[1 3]
 [2 4]]


In [12]:
# dot()

a = np.array([[1, 2], [3, 4]])
b = np.array([[2, 0], [1, 2]])

print("dot/multiplication:", a.dot(b))

dot/multiplication: [[ 4  4]
 [10  8]]


In [13]:
# random.rand()

a = np.random.rand(2, 3)

print("random rand:", a)

random rand: [[0.84833675 0.70674932 0.19022133]
 [0.75643108 0.11005647 0.82895335]]
